version: "3.9"

x-logging: &logging
 driver: "json-file"
 options:
   max-size: "1000m"
   max-file: "1"



services:
  php:
    build: .
    networks: 
     - net
    logging: *logging
    
    healthcheck:
        test: ["CMD-SHELL","curl -f http://nginx/ | grep works"]
        interval: 1s
        timeout: 3s
        retries: 30

    volumes:
       - ./www:/var/www
       - ./www:/var/www/html/

  nginx:
    image: "nginx"
    networks:
      - net
    logging: *logging
    ports: 
        - "4000:80"
    deploy:
       resources:
          limits:
             cpus: "1"
             memory: "20M"
    volumes:
       - ./nginx/:/etc/nginx/conf.d/
       - ./www:/var/www
    
    depends_on:
       - php    


networks:
  net:
