version: "3.9"

x-logging: &logging
 driver: "json-file"
 options:
   max-size: "1000m"
   max-file: "1"



services:
  php:
    build: .
    ports:
     - "127.0.0.1:5000:5000"
    depends_on: 
       nginx:
         condition: service_healthy
    networks: 
     - net
    logging: *logging

  nginx:
    image: "nginx"
    networks:
      - net
    logging: *logging
    ports: 
        - "4000:80"
    deploy:
       resources:
          limits:
             cpus: "${DOCKER_REDIS_CPU:-0}"
             memory: "${DOCKER_REDIS_MEMORY:-0}"
    healthcheck: 
        test: ["CMD-SHELL","curl -f http://nginx/"] 
        interval: 1s
        timeout: 3s
        retries: 30 

networks:
  net:
