version: "3.9"

x-logging: &logging
 driver: "json-file"
 options:
   max-size: "1000m"
   max-file: "1"



services:
  php:
    build: .
    depends_on: 
       nginx:
         condition: service_healthy
    networks: 
     - net
    logging: *logging
    restart: always

  nginx:
    image: "nginx"
    networks:
      - net
    logging: *logging
    ports: 
        - "4000:80"
    deploy:
       resources:
          limits:
             cpus: "1"
             memory: "20M"
    volumes:
       - ./nginx/dev.conf:/etc/nginx/nginx.conf
       - ./www:/var/www

    healthcheck: 
        test: ["CMD-SHELL","curl -f http://nginx/ | grep works"] 
        interval: 1s
        timeout: 3s
        retries: 30 

networks:
  net:
